version: '3.8'

services:
  music-service:
    image: neiln3121/music-service
    ports:
      - 8080:8080
    environment:
      DB_SERVER: mssql
      DB_PORT: 1433
      DB_USER: SA
      DB_PASSWORD: Pass@word123
      DB_NAME: master
      PORT: 8080

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: Pass@word123
      ACCEPT_EULA: Y
    